# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brand New Developer
email: chunter@formationtech.com
description: > # this means to ignore newlines until "baseurl:"
  I work full time as a Systems Analyst for Formation Technology (www.formationtech.com). I'm starting to dabble in web & application development. This page is going to serve as a landing spot for my development portfoilio as I gain more experience in the development world. In the meantime, should you find yourself in need of support in all things Technology, we would love to chat with you!
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.formationtech.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: itschunter
github_username:  chunter519

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
